/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

use std::any::TypeId;
use std::marker::PhantomData;

use tvm_ffi_sys::TVMFFITypeIndex as TypeIndex;

use crate::AnyCompatible;

/// A call-site-local arm number generated by `match_any!`.
#[doc(hidden)]
pub type ArmId = u32;

/// Maps runtime object type indices to call-site-local arm numbers.
///
/// The table stores only [`ArmId`] values. Arm bodies remain native branches in
/// the macro expansion and are never stored as functions or closures.
#[doc(hidden)]
pub struct LeafLookupTable {
    pattern_list_id: TypeId,
    arm_by_type_index: Box<[(i32, ArmId)]>,
}

impl LeafLookupTable {
    #[doc(hidden)]
    pub fn build(pattern_list_id: TypeId, entries: &[(i32, ArmId)]) -> Self {
        assert!(
            !entries.is_empty(),
            "match_any! leaf lookup requires at least one arm"
        );
        for &(type_index, _) in entries {
            assert!(
                type_index >= TypeIndex::kTVMFFIStaticObjectBegin as i32,
                "match_any! leaf pattern returned a non-object type index"
            );
        }

        let mut arm_by_type_index = entries.to_vec();
        // Stable sorting plus deduplication preserves the first arm for a
        // duplicate runtime type index.
        arm_by_type_index.sort_by_key(|&(type_index, _)| type_index);
        arm_by_type_index.dedup_by_key(|entry| entry.0);

        Self {
            pattern_list_id,
            arm_by_type_index: arm_by_type_index.into_boxed_slice(),
        }
    }

    #[doc(hidden)]
    #[inline(always)]
    pub fn lookup(&self, pattern_list_id: TypeId, type_index: i32) -> Result<Option<ArmId>, ()> {
        if self.pattern_list_id != pattern_list_id {
            return Err(());
        }

        Ok(self
            .arm_by_type_index
            .binary_search_by_key(&type_index, |&(entry_type_index, _)| entry_type_index)
            .ok()
            .map(|offset| self.arm_by_type_index[offset].1))
    }
}

/// Type-level list used to collect leaf object-pattern metadata.
#[doc(hidden)]
pub trait LeafPatternList: 'static {
    #[doc(hidden)]
    const ALL_EXACT_LEAF: bool;

    #[doc(hidden)]
    fn fill_leaf_type_indices(out: &mut [i32]);
}

impl LeafPatternList for () {
    const ALL_EXACT_LEAF: bool = true;

    fn fill_leaf_type_indices(out: &mut [i32]) {
        debug_assert!(out.is_empty());
    }
}

impl<Head, Tail> LeafPatternList for (Head, Tail)
where
    Head: AnyCompatible + 'static,
    Tail: LeafPatternList,
{
    const ALL_EXACT_LEAF: bool = Head::MATCH_ANY_EXACT && Tail::ALL_EXACT_LEAF;

    fn fill_leaf_type_indices(out: &mut [i32]) {
        let (head, tail) = out
            .split_first_mut()
            .expect("match_any! pattern metadata length mismatch");
        *head = Head::match_any_exact_type_index();
        Tail::fill_leaf_type_indices(tail);
    }
}

/// Probe used by the macro to retain ordered matching for non-leaf patterns.
#[doc(hidden)]
pub struct LeafPatternProbe<T>(PhantomData<fn() -> T>);

impl<T> LeafPatternProbe<T> {
    #[doc(hidden)]
    pub const fn new() -> Self {
        Self(PhantomData)
    }
}

/// Leaf metadata with an autoref fallback for non-`AnyCompatible` patterns.
#[doc(hidden)]
pub trait LeafPatternMetadata {
    #[doc(hidden)]
    fn leaf_pattern_list_id(&self) -> Option<TypeId> {
        None
    }

    #[doc(hidden)]
    fn fill_leaf_type_indices(&self, _out: &mut [i32]) {}
}

impl<T> LeafPatternMetadata for &LeafPatternProbe<T> {}

impl<T: LeafPatternList> LeafPatternMetadata for LeafPatternProbe<T> {
    fn leaf_pattern_list_id(&self) -> Option<TypeId> {
        T::ALL_EXACT_LEAF.then(TypeId::of::<T>)
    }

    fn fill_leaf_type_indices(&self, out: &mut [i32]) {
        T::fill_leaf_type_indices(out);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Array, Module, Tensor};

    #[test]
    fn lookup_table_maps_runtime_indices_to_local_arm_ids() {
        const ARM_0: ArmId = 0;
        const ARM_1: ArmId = 1;
        const ARM_2: ArmId = 2;
        let pattern_list_id = TypeId::of::<(i32, i64, f32)>();
        let table =
            LeafLookupTable::build(pattern_list_id, &[(73, ARM_0), (73, ARM_1), (75, ARM_2)]);

        assert_eq!(table.lookup(pattern_list_id, 73), Ok(Some(ARM_0)));
        assert_eq!(table.lookup(pattern_list_id, 72), Ok(None));
        assert_eq!(table.lookup(pattern_list_id, 74), Ok(None));
        assert_eq!(table.lookup(pattern_list_id, 75), Ok(Some(ARM_2)));
        assert_eq!(table.lookup(pattern_list_id, 76), Ok(None));
    }

    #[test]
    fn a_generic_pattern_list_cannot_reuse_another_lists_table() {
        let pattern_list_id = TypeId::of::<(i32, i64)>();
        let table = LeafLookupTable::build(pattern_list_id, &[(73, 0), (75, 1)]);

        assert_eq!(table.lookup(TypeId::of::<(u8, u16)>(), 73), Err(()));
    }

    #[test]
    fn metadata_only_accepts_exact_leaf_patterns() {
        type Leaf = (Module, ());
        let leaf = LeafPatternProbe::<Leaf>::new();
        let mut type_indices = [0; 1];
        assert!((&leaf).leaf_pattern_list_id().is_some());
        (&leaf).fill_leaf_type_indices(&mut type_indices);
        assert!(type_indices[0] >= TypeIndex::kTVMFFIStaticObjectBegin as i32);

        type Parameterized = (Array<i64>, ());
        let parameterized = LeafPatternProbe::<Parameterized>::new();
        assert!((&parameterized).leaf_pattern_list_id().is_none());

        type NonFinal = (Tensor, ());
        let non_final = LeafPatternProbe::<NonFinal>::new();
        assert!((&non_final).leaf_pattern_list_id().is_none());

        struct NoAnyCompatibleMetadata;
        type Custom = (NoAnyCompatibleMetadata, ());
        let custom = LeafPatternProbe::<Custom>::new();
        assert!((&custom).leaf_pattern_list_id().is_none());
    }
}
