/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

use std::any::TypeId;
use std::marker::PhantomData;

use tvm_ffi_sys::TVMFFITypeIndex as TypeIndex;

use crate::{AnyCompatible, AnyView};

/// A call-site-local arm number generated by `match_any!`.
#[doc(hidden)]
pub type ArmId = u32;

/// Conversion adapter used by `match_any!` typed arms.
#[doc(hidden)]
pub struct PatternConversionProbe<T>(PhantomData<fn() -> T>);

impl<T> PatternConversionProbe<T> {
    #[doc(hidden)]
    pub const fn new() -> Self {
        Self(PhantomData)
    }
}

/// Prefer the lightweight `AnyCompatible` conversion while retaining a
/// `TryInto` fallback for custom matcher types.
#[doc(hidden)]
pub trait PatternConversion<'a, T> {
    #[doc(hidden)]
    fn try_convert(&self, view: AnyView<'a>) -> Result<T, ()>;

    /// Convert after exact-leaf lookup has established that `view` matches
    /// `T`. Custom `TryInto` matchers retain their checked conversion.
    ///
    /// # Safety
    ///
    /// The caller must establish the `AnyCompatible::MATCH_ANY_EXACT`
    /// contract before using the unchecked implementation.
    #[doc(hidden)]
    unsafe fn try_convert_after_exact_match(&self, view: AnyView<'a>) -> Result<T, ()> {
        self.try_convert(view)
    }
}

impl<'a, T: AnyCompatible> PatternConversion<'a, T> for PatternConversionProbe<T> {
    #[inline(always)]
    fn try_convert(&self, view: AnyView<'a>) -> Result<T, ()> {
        if T::MATCH_ANY_EXACT {
            if view.type_index() == T::match_any_exact_type_index() {
                Ok(unsafe { crate::any::copy_from_any_view_after_check::<T>(&view) })
            } else {
                Err(())
            }
        } else {
            crate::any::try_cast_from_any_view::<T>(&view)
        }
    }

    #[inline(always)]
    unsafe fn try_convert_after_exact_match(&self, view: AnyView<'a>) -> Result<T, ()> {
        Ok(crate::any::copy_from_any_view_after_check::<T>(&view))
    }
}

impl<'a, T> PatternConversion<'a, T> for &PatternConversionProbe<T>
where
    AnyView<'a>: TryInto<T>,
{
    #[inline(always)]
    fn try_convert(&self, view: AnyView<'a>) -> Result<T, ()> {
        view.try_into().map_err(|_| ())
    }
}

/// Runtime type-index lookup for one `match_any!` call site.
///
/// A successful lookup returns the matching position as a call-site-local
/// [`ArmId`]. Arm bodies remain native branches in the macro expansion and are
/// never stored as functions or closures.
#[doc(hidden)]
pub struct LeafLookupTable {
    pattern_list_id: TypeId,
    storage: LeafLookupStorage,
}

// Bound the dense payload allocated by one call site. Wider index spaces use
// the sparse fallback instead of allocating in proportion to TypeIndex.
const MAX_DIRECT_LOOKUP_BYTES: usize = 4096;
// In randomized x86-64 O3 measurements through 128 arms, sorted lookup starts
// winning near 84 arms depending on layout; use 96 as a conservative,
// benchmark-tunable crossover.
const MIN_SORTED_LOOKUP_ARMS: usize = 96;
const NO_ARM_ID: u8 = u8::MAX;

enum LeafLookupStorage {
    /// `type_index - base` directly indexes an encoded `ArmId`.
    Direct { base: i32, arm_ids: Box<[u8]> },
    /// A source-ordered scan is cheaper than binary search at medium sizes.
    Linear(Box<[i32]>),
    /// Large sparse pattern lists use sorted binary search.
    Sorted(Box<[(i32, ArmId)]>),
}

#[cold]
#[inline(never)]
fn build_leaf_lookup_storage(type_indices: &[i32]) -> LeafLookupStorage {
    assert!(
        !type_indices.is_empty(),
        "match_any! leaf lookup requires at least one arm"
    );
    assert!(
        type_indices
            .iter()
            .all(|&type_index| type_index >= TypeIndex::kTVMFFIStaticObjectBegin as i32),
        "match_any! leaf pattern returned a non-object type index"
    );
    let min_type_index = *type_indices.iter().min().unwrap();
    let max_type_index = *type_indices.iter().max().unwrap();
    let span = usize::try_from(i64::from(max_type_index) - i64::from(min_type_index) + 1)
        .expect("match_any! leaf pattern returned an invalid type-index span");

    if type_indices.len() <= u8::MAX as usize && span <= MAX_DIRECT_LOOKUP_BYTES {
        let mut arm_ids = vec![NO_ARM_ID; span];
        for (arm_id, &type_index) in type_indices.iter().enumerate() {
            let offset = (type_index - min_type_index) as usize;
            let slot = &mut arm_ids[offset];
            // Keep the first source arm for duplicate runtime indices.
            if *slot == NO_ARM_ID {
                *slot = arm_id as u8;
            }
        }
        LeafLookupStorage::Direct {
            base: min_type_index,
            arm_ids: arm_ids.into_boxed_slice(),
        }
    } else if type_indices.len() < MIN_SORTED_LOOKUP_ARMS {
        LeafLookupStorage::Linear(type_indices.into())
    } else {
        let mut entries = type_indices
            .iter()
            .copied()
            .enumerate()
            .map(|(arm_id, type_index)| (type_index, arm_id as ArmId))
            .collect::<Vec<_>>();
        // Sorting by ArmId within equal indices keeps the first source arm.
        entries.sort_unstable();
        entries.dedup_by_key(|entry| entry.0);
        LeafLookupStorage::Sorted(entries.into_boxed_slice())
    }
}

#[inline(always)]
fn lookup_linear_leaf(type_indices: &[i32], type_index: i32) -> Option<ArmId> {
    type_indices
        .iter()
        .position(|&candidate| candidate == type_index)
        .map(|arm_id| arm_id as ArmId)
}

#[inline(never)]
fn lookup_sorted_leaf(entries: &[(i32, ArmId)], type_index: i32) -> Option<ArmId> {
    entries
        .binary_search_by_key(&type_index, |&(candidate, _)| candidate)
        .ok()
        .map(|index| entries[index].1)
}

impl LeafLookupTable {
    #[doc(hidden)]
    #[cold]
    #[inline(never)]
    pub fn build(pattern_list_id: TypeId, type_indices: &[i32]) -> Self {
        Self {
            pattern_list_id,
            storage: build_leaf_lookup_storage(type_indices),
        }
    }

    #[doc(hidden)]
    #[inline(always)]
    pub fn lookup(&self, pattern_list_id: TypeId, type_index: i32) -> Result<Option<ArmId>, ()> {
        if self.pattern_list_id != pattern_list_id {
            return Err(());
        }
        Ok(match &self.storage {
            LeafLookupStorage::Direct { base, arm_ids } => {
                let offset = type_index.wrapping_sub(*base) as usize;
                let arm_id = arm_ids.get(offset).copied().unwrap_or(NO_ARM_ID);
                (arm_id != NO_ARM_ID).then(|| ArmId::from(arm_id))
            }
            LeafLookupStorage::Linear(type_indices) => lookup_linear_leaf(type_indices, type_index),
            LeafLookupStorage::Sorted(entries) => lookup_sorted_leaf(entries, type_index),
        })
    }
}

/// Type-level list used to collect leaf object-pattern metadata.
#[doc(hidden)]
pub trait LeafPatternList: 'static {
    #[doc(hidden)]
    const ALL_EXACT_LEAF: bool;

    #[doc(hidden)]
    fn fill_leaf_type_indices(out: &mut [i32]);
}

impl LeafPatternList for () {
    const ALL_EXACT_LEAF: bool = true;

    #[inline(always)]
    fn fill_leaf_type_indices(out: &mut [i32]) {
        debug_assert!(out.is_empty());
    }
}

impl<Head, Tail> LeafPatternList for (Head, Tail)
where
    Head: AnyCompatible + 'static,
    Tail: LeafPatternList,
{
    const ALL_EXACT_LEAF: bool = Head::MATCH_ANY_EXACT && Tail::ALL_EXACT_LEAF;

    #[inline(always)]
    fn fill_leaf_type_indices(out: &mut [i32]) {
        let (head, tail) = out
            .split_first_mut()
            .expect("match_any! pattern metadata length mismatch");
        *head = Head::match_any_exact_type_index();
        Tail::fill_leaf_type_indices(tail);
    }
}

/// Probe used by the macro to retain ordered matching for non-leaf patterns.
#[doc(hidden)]
pub struct LeafPatternProbe<T>(PhantomData<fn() -> T>);

impl<T> LeafPatternProbe<T> {
    #[doc(hidden)]
    pub const fn new() -> Self {
        Self(PhantomData)
    }
}

/// Leaf metadata with an autoref fallback for non-`AnyCompatible` patterns.
#[doc(hidden)]
pub trait LeafPatternMetadata {
    #[doc(hidden)]
    fn leaf_pattern_list_id(&self) -> Option<TypeId> {
        None
    }

    #[doc(hidden)]
    fn fill_leaf_type_indices(&self, _out: &mut [i32]) {}
}

impl<T> LeafPatternMetadata for &LeafPatternProbe<T> {}

impl<T: LeafPatternList> LeafPatternMetadata for LeafPatternProbe<T> {
    #[inline(always)]
    fn leaf_pattern_list_id(&self) -> Option<TypeId> {
        T::ALL_EXACT_LEAF.then(TypeId::of::<T>)
    }

    #[inline(always)]
    fn fill_leaf_type_indices(&self, out: &mut [i32]) {
        T::fill_leaf_type_indices(out);
    }
}
